apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: rest-pod
  name: rest-pod
spec:
  containers:
  - image: nginx
    name: rest-pod
    securityContext:
      privileged: true
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
